In [1]:
import time
import requests
import pandas as pd
from pathlib import Path
from scipy.stats import fisher_exact
from statsmodels.stats.multitest import multipletests

main_dir = Path("C:/Users/gabri/Documents/Data_projects/MCcharactertization/ROSMAP/Top_sets/Set309")
#main_dir = Path('/Users/ga0028vi/Documents/MCcharactertization/ROSMAP/Top_sets/Set309')

infile = Path(main_dir, "_set_data/PLSsig_genelists_long.csv")

out_dir =Path(main_dir, "STRING_AGM_analysis/Annotations")
out_dir.mkdir(parents=True, exist_ok=True)

agm_df = pd.read_csv(infile)
print(agm_df.head())

                                  AGM_ID        gene
0  Excitatory_ExcL45RORBGABRG1_Cluster_0       ISG15
1  Excitatory_ExcL45RORBGABRG1_Cluster_0     FAM131C
2  Excitatory_ExcL45RORBGABRG1_Cluster_0  AL445685.1
3  Excitatory_ExcL45RORBGABRG1_Cluster_0    ARHGAP29
4  Excitatory_ExcL45RORBGABRG1_Cluster_0     C1orf61

## Ensembl queries

In [2]:
# query Ensembl in batches
def query_ensembl_gene_biotypes(
    genes,
    species="homo_sapiens",
    batch_size=500,
    sleep_time=0.2,
):
    """
    Query Ensembl REST API for gene biotypes using gene symbols.

    Parameters
    ----------
    genes : list-like
        Gene symbols, e.g. ["ISG15", "AL445685.1"].
    species : str
        Ensembl species name. For human, use "homo_sapiens".
    batch_size : int
        Number of symbols per API request.
    sleep_time : float
        Pause between requests to be polite to the API.

    Returns
    -------
    pd.DataFrame
        Annotation table with one row per returned gene.
    """

    genes = (
        pd.Series(genes)
        .dropna()
        .astype(str)
        .str.strip()
        .unique()
        .tolist()
    )

    url = f"https://rest.ensembl.org/lookup/symbol/{species}"

    headers = {
        "Content-Type": "application/json",
        "Accept": "application/json"
    }

    all_rows = []

    for i in range(0, len(genes), batch_size):
        batch = genes[i:i + batch_size]

        payload = {
            "symbols": batch
        }

        response = requests.post(
            url,
            headers=headers,
            json=payload,
            timeout=30
        )

        if response.status_code != 200:
            print(f"Batch {i // batch_size + 1} failed with status {response.status_code}")
            print(response.text[:500])
            continue

        data = response.json()

        for query_symbol, hit in data.items():
            if hit is None:
                continue

            all_rows.append({
                "gene": query_symbol,
                "ensembl_gene_id": hit.get("id"),
                "display_name": hit.get("display_name"),
                "description": hit.get("description"),
                "biotype": hit.get("biotype"),
                "object_type": hit.get("object_type"),
                "source": hit.get("source"),
                "seq_region_name": hit.get("seq_region_name"),
                "start": hit.get("start"),
                "end": hit.get("end"),
                "strand": hit.get("strand")
            })

        print(f"Queried {min(i + batch_size, len(genes))}/{len(genes)} genes")
        time.sleep(sleep_time)

    annot_df = pd.DataFrame(all_rows)

    return annot_df

In [3]:
# Query unique genes
unique_genes = agm_df["gene"].dropna().unique()

annot_df = query_ensembl_gene_biotypes(unique_genes)

print(annot_df["biotype"].value_counts(dropna=False))


# Merge annotation back to AGM table
agm_annotated_df = agm_df.merge(annot_df, on="gene", how="left")
agm_annotated_df["annotation_found"] = agm_annotated_df["ensembl_gene_id"].notna()

# Save the intermediary file from ensembl with the OG gene names
outfile = Path(out_dir, "AGM_gene_list_long_with_biotypes.csv")
agm_annotated_df.to_csv(outfile, index=False)
print(f"Saved: {outfile}")

# Save missing gene annotations for HGNC
miss_file = Path(out_dir, "AGM_genes_missing_annotation.csv")
missing_df = (agm_annotated_df.loc[~agm_annotated_df["annotation_found"], ["gene"]].drop_duplicates().sort_values("gene"))
missing_df.to_csv(miss_file, index=False)
print(f"Saved: {miss_file}")

Queried 500/2004 genes
Queried 1000/2004 genes
Queried 1500/2004 genes
Queried 2000/2004 genes
Queried 2004/2004 genes
biotype
protein_coding    1613
lncRNA             128
TR_C_gene            1
Name: count, dtype: int64
Saved: C:\Users\gabri\Documents\Data_projects\MCcharactertization\ROSMAP\Top_sets\Set309\STRING_AGM_analysis\Annotations\AGM_gene_list_long_with_biotypes.csv
Saved: C:\Users\gabri\Documents\Data_projects\MCcharactertization\ROSMAP\Top_sets\Set309\STRING_AGM_analysis\Annotations\AGM_genes_missing_annotation.csv

# Cleaning up the gene list

In [19]:
# First-pass Ensembl annotation
ensembl_file = out_dir / "AGM_gene_list_long_with_biotypes.csv"
# HGNC symbol checker output
hgnc_file = out_dir / "hgnc-symbol-check.csv"

hgnc_df = pd.read_csv(hgnc_file, skiprows=1)
agm_df = pd.read_csv(infile)
ensembl_df = pd.read_csv(ensembl_file)

In [20]:
ensembl_df = ensembl_df.rename(columns={"gene": "gene_og"})
ensembl_df["gene_renamed"] = ensembl_df["gene_og"]


#keep only HGNC rows where Input is not 0
hgnc_df = hgnc_df[hgnc_df["Input"] != 0].copy()


# merge HGNC Approved symbol onto ensembl_df
ensembl_df = ensembl_df.merge(hgnc_df[["Input", "Approved symbol"]],
                              left_on="gene_renamed",
                              right_on="Input",
                              how="left")

#Replace gene_renamed with HGNC Approved symbol
ensembl_df.loc[ensembl_df["Approved symbol"].notna(),"gene_renamed"] = ensembl_df.loc[ensembl_df["Approved symbol"].notna(),"Approved symbol"]


# bool if HGNC changed the gene name
ensembl_df["gene_name_changed_by_hgnc"] = (ensembl_df["gene_og"] != ensembl_df["gene_renamed"])

# Drop temp columns
ensembl_df = ensembl_df.drop(columns=["Input", "Approved symbol"])

In [21]:
genes_to_rerun = (ensembl_df.loc[(~ensembl_df["annotation_found"]) 
                                 & (ensembl_df["gene_name_changed_by_hgnc"]),"gene_renamed"]
                  .drop_duplicates().tolist())

In [23]:
# Rerun ENSEMBL
# genes that failed first-pass Ensembl annotation,
# but now have an HGNC-updated symbol
print("Genes to re-query:", len(genes_to_rerun))
print(genes_to_rerun[:10])

rerun_annot_df = query_ensembl_gene_biotypes(genes_to_rerun)

print(rerun_annot_df.head())
print(rerun_annot_df["biotype"].value_counts(dropna=False))

Genes to re-query: 43
['MIR9-1HG', 'NICOL1', 'MARCHF1', 'TAFA2', 'CCN2', 'CCN2-AS1', 'ABTB3', 'MYL11', 'NHERF1', 'H2AC6']
Queried 43/43 genes
      gene  ensembl_gene_id display_name  \
0   NHERF1  ENSG00000109062       NHERF1
1     BBLN  ENSG00000171159         BBLN
2    CCDST  ENSG00000236427        CCDST
3  CAV2-DT  ENSG00000237813      CAV2-DT
4    AFG2A  ENSG00000145375        AFG2A

                                         description         biotype  \
0  NHERF family PDZ scaffold protein 1 [Source:HG...  protein_coding
1  bublin coiled coil protein [Source:HGNC Symbol...  protein_coding
2  cervical cancer associated DHX9 suppressive tr...          lncRNA
3  CAV2 divergent transcript [Source:HGNC Symbol;...          lncRNA
4  AFG2 AAA ATPase homolog A [Source:HGNC Symbol;...  protein_coding

  object_type          source seq_region_name      start        end  strand
0        Gene  ensembl_havana              17   74748619   74769360       1
1        Gene  ensembl_havana               9  128160265  128163924       1
2        Gene          havana               1  152165553  152445456       1
3        Gene          havana               7  116238260  116499537      -1
4        Gene  ensembl_havana               4  122923070  123319433       1
biotype
protein_coding    27
lncRNA            15
Name: count, dtype: int64

In [24]:
# make copy just in case
updated_df = ensembl_df.copy()
rerun_tmp = rerun_annot_df.rename(columns={"gene": "gene_renamed"}).copy()

In [25]:
annot_cols = ["ensembl_gene_id", "display_name", "description", "biotype", "object_type",
              "source", "seq_region_name", "start", "end", "strand"]

In [26]:
#set index to gene_renamed so matching happens by the renamed HGNC symbol
updated_df = updated_df.set_index("gene_renamed")
rerun_tmp = rerun_tmp.set_index("gene_renamed")

#replace annotation columns if rerun annotation exists
updated_df.update(rerun_tmp[annot_cols])

#bring gene_renamed back as a normal column
updated_df = updated_df.reset_index()

In [27]:
#update the annotation if
updated_df["annotation_found"] = updated_df["ensembl_gene_id"].notna()

In [28]:
# Add ncRNA / protein-coding flags
lncRNA_biotypes = {
    "lncRNA",
    "lincRNA",
    "antisense",
    "sense_intronic",
    "sense_overlapping",
    "processed_transcript",
    "3prime_overlapping_ncRNA",
    "macro_lncRNA",
    "bidirectional_promoter_lncRNA",
    "non_coding"
}

small_ncRNA_biotypes = {
    "miRNA",
    "snRNA",
    "snoRNA",
    "rRNA",
    "misc_RNA",
    "scaRNA",
    "scRNA",
    "ribozyme",
    "sRNA",
    "vault_RNA",
    "Mt_rRNA",
    "Mt_tRNA"
}

ncRNA_biotypes = lncRNA_biotypes.union(small_ncRNA_biotypes)

updated_df["is_lncRNA"] = updated_df["biotype"].isin(lncRNA_biotypes)
updated_df["is_any_ncRNA"] = updated_df["biotype"].isin(ncRNA_biotypes)
updated_df["is_protein_coding"] = updated_df["biotype"].eq("protein_coding")

In [29]:
cols_order = ["AGM_ID",
              "gene_og",
              "gene_renamed",
              "gene_name_changed_by_hgnc",
              "ensembl_gene_id",
              "display_name",
              "description",
              "biotype",
              "is_lncRNA",
              "is_any_ncRNA",
              "is_protein_coding",
              "object_type",
              "source",
              "seq_region_name",
              "start",
              "end",
              "strand",
              "annotation_found"
              ]

updated_df = updated_df[cols_order].copy()

In [30]:
print("\nAnnotation found:")
print(updated_df["annotation_found"].value_counts(dropna=False))

print("\nBiotypes:")
print(updated_df["biotype"].value_counts(dropna=False).head(30))

print("\nHGNC renamed genes:")
print(updated_df["gene_name_changed_by_hgnc"].value_counts(dropna=False))

still_missing = (
    updated_df
    .loc[~updated_df["annotation_found"], "gene_og"]
    .dropna()
    .drop_duplicates()
    .sort_values()
)

print("\nStill missing:", len(still_missing))
print(still_missing.head(100).to_list())

Annotation found:
annotation_found
True     2364
False     312
Name: count, dtype: int64

Biotypes:
biotype
protein_coding    2181
NaN                312
lncRNA             182
TR_C_gene            1
Name: count, dtype: int64

HGNC renamed genes:
gene_name_changed_by_hgnc
False    2616
True       60
Name: count, dtype: int64

Still missing: 221
['AC003988.1', 'AC003991.1', 'AC004158.1', 'AC004594.1', 'AC004852.2', 'AC004949.1', 'AC005064.1', 'AC005154.5', 'AC005537.1', 'AC005726.5', 'AC005828.3', 'AC005842.1', 'AC006059.1', 'AC006148.1', 'AC006305.1', 'AC006450.3', 'AC007091.1', 'AC007319.1', 'AC007344.1', 'AC007402.1', 'AC007614.1', 'AC007656.1', 'AC007785.1', 'AC008014.1', 'AC008105.3', 'AC008415.1', 'AC008574.1', 'AC008691.1', 'AC008780.1', 'AC009063.2', 'AC009163.1', 'AC009226.1', 'AC009501.1', 'AC010099.4', 'AC010127.1', 'AC010260.1', 'AC010967.1', 'AC011287.1', 'AC011468.3', 'AC012593.1', 'AC016152.1', 'AC016597.1', 'AC016687.2', 'AC016716.2', 'AC016722.2', 'AC018682.1', 'AC019068.1', 'AC019211.1', 'AC020661.3', 'AC021504.1', 'AC022126.1', 'AC022523.1', 'AC022639.1', 'AC022784.6', 'AC024230.1', 'AC024560.3', 'AC024901.1', 'AC025043.1', 'AC025159.1', 'AC025470.2', 'AC025810.1', 'AC026316.5', 'AC026979.2', 'AC027018.1', 'AC027097.2', 'AC027117.2', 'AC027796.4', 'AC037486.1', 'AC046136.1', 'AC055811.2', 'AC060765.1', 'AC062021.1', 'AC067956.1', 'AC068025.2', 'AC068205.1', 'AC068533.4', 'AC068631.2', 'AC068633.1', 'AC072062.1', 'AC073050.1', 'AC073316.1', 'AC073332.1', 'AC073365.1', 'AC073941.1', 'AC074327.1', 'AC079098.1', 'AC079362.1', 'AC079380.1', 'AC079447.1', 'AC084032.1', 'AC087280.2', 'AC087857.1', 'AC090124.1', 'AC090125.1', 'AC090403.1', 'AC090502.1', 'AC090568.2', 'AC091078.1', 'AC091826.2', 'AC091885.2']

In [31]:
# Final output
final_file = out_dir / "AGM_gene_list_long_with_biotypes_HGNC_rescued.csv"
updated_df.to_csv(final_file, index=False)

In [33]:
updated_df['is_unannotated'] = ~updated_df["annotation_found"]

In [35]:
gsea_gene_lists = (
    updated_df
    .loc[updated_df["annotation_found"], ["AGM_ID", "gene_renamed"]]
    .dropna()
    .drop_duplicates()
    .sort_values(["AGM_ID", "gene_renamed"])
)

gsea_gene_lists.to_csv(Path(out_dir, "PLSgenelist_long_HGNCcorrected.csv"), index=False)

## Analysis of enrichment

In [38]:
category = "is_lncRNA"

all_genes = set(updated_df["gene_og"].dropna().unique())

In [ ]:
len(all_genes)

gene_status = (
    updated_df[["gene_og", category]]
    .drop_duplicates("gene_og")
    .set_index("gene_og")[category]
    .to_dict()
)

{'ISG15': False,
 'FAM131C': False,
 'AL445685.1': False,
 'ARHGAP29': False,
 'C1orf61': True,
 'PCP4L1': False,
 'CHI3L1': False,
 'GCSAML': False,
 'HPCAL1': False,
 'LINC00276': True,
 'RASGRP3': False,
 'EPAS1': False,
 'LINC01798': True,
 'ARHGAP15': False,
 'GAD1': False,
 'LINC01090': True,
 'PARD3B': False,
 'TMBIM1': False,
 'SLC6A1-AS1': True,
 'FEZF2': False,
 'AC026316.5': False,
 'IGF2BP2': False,
 'SST': False,
 'FAM114A1': False,
 'RBM47': False,
 'REST': False,
 'NDST4': False,
 'LINC01099': True,
 'LINC01194': True,
 'MYO10': False,
 'FYB1': False,
 'AC114947.2': False,
 'HSPB3': False,
 'SETD9': False,
 'S100Z': False,
 'HOMER1': False,
 'ISOC1': False,
 'FGF1': False,
 'GPX3': False,
 'FAT2': False,
 'LCP2': False,
 'KCNIP1': False,
 'TUBB2B': False,
 'GCNT2': False,
 'SOX4': False,
 'HLA-A': False,
 'HLA-B': False,
 'HLA-DPA1': False,
 'TENT5A': False,
 'PKIB': False,
 'FABP7': False,
 'SAMD3': False,
 'UTRN': False,
 'AL160162.1': False,
 'AC005154.5': False,
 'ELMO1-AS1': True,
 'PHKG1': False,
 'NPTX2': False,
 'VGF': False,
 'LINC01007': True,
 'GLRA2': False,
 'Z96074.1': False,
 'HMGB3': False,
 'MSR1': False,
 'ADAM28': False,
 'DUSP4': False,
 'LYN': False,
 'PENK': False,
 'CRH': False,
 'C8orf34': False,
 'SNTB1': False,
 'ARC': False,
 'SLC39A4': False,
 'DOCK8': False,
 'LURAP1L-AS1': True,
 'BNC2': False,
 'STOM': False,
 'ENG': False,
 'IFITM10': False,
 'PHLDA2': False,
 'SOX6': False,
 'BDNF': False,
 'ABTB2': False,
 'TSPAN18': False,
 'LRP4-AS1': True,
 'AHNAK': False,
 'AP001160.1': False,
 'TRPT1': False,
 'TM7SF2': False,
 'SLCO2B1': False,
 'SLC39A12': False,
 'PCDH15': False,
 'CTNNA3': False,
 'PLAC9': False,
 'ACTA2': False,
 'PPP1R3C': False,
 'PLCE1': False,
 'NR4A1': False,
 'CPM': False,
 'AC084032.1': False,
 'DUSP6': False,
 'ASCL1': False,
 'AC117503.1': False,
 'FLT3': False,
 'FLT1': False,
 'KLHL1': False,
 'LGALS3': False,
 'AL117190.2': False,
 'MKRN3': False,
 'AC073941.1': False,
 'AC245033.2': False,
 'AGBL1': False,
 'MCTP2': False,
 'HBA2': False,
 'MSRB1': False,
 'AC099489.1': False,
 'MYH11': False,
 'AC016597.1': False,
 'PYDC1': False,
 'NQO1': False,
 'ZFHX3': False,
 'LDHD': False,
 'ACAP1': False,
 'TRAF4': False,
 'AC068025.2': False,
 'CA4': False,
 'SSTR2': False,
 'COLEC12': False,
 'GNAL': False,
 'SLC24A3': False,
 'TP53TG5': False,
 'RIPOR3': False,
 'NFATC2': False,
 'PMEPA1': False,
 'PLIN3': False,
 'AC092069.1': False,
 'LINC01841': True,
 'GMFG': False,
 'SERTAD1': False,
 'NECTIN2': False,
 'GRIN2D': False,
 'CECR2': False,
 'Z99774.1': False,
 'PPARA': False,
 'MASP2': False,
 'SH3BGRL3': False,
 'PDC': False,
 'ERVMER61-1': False,
 'LINC00486': True,
 'AC018682.1': False,
 'AC009501.1': False,
 'AC016716.2': False,
 'USP39': False,
 'EIF5B': False,
 'LSAMP-AS1': True,
 'P2RY14': False,
 'IGSF10': False,
 'AC125613.1': False,
 'AC068631.2': False,
 'APOD': False,
 'C4orf48': False,
 'AC104827.1': False,
 'AC097478.1': False,
 'PDE5A': False,
 'HHIP': False,
 'SCRG1': False,
 'AC091885.2': False,
 'AC010260.1': False,
 'ABCB1': False,
 'SLC26A5': False,
 'AC004594.1': False,
 'LINC00513': True,
 'LINC02153': True,
 'AC026979.2': False,
 'AC027018.1': False,
 'CA1': False,
 'LY6H': False,
 'AL162231.1': False,
 'CKS2': False,
 'GRIN3A': False,
 'AC006450.3': False,
 'AL157938.3': False,
 'LYVE1': False,
 'LRP4': False,
 'ACP2': False,
 'SPI1': False,
 'WDR74': False,
 'STARD10': False,
 'AP001825.1': False,
 'CRYAB': False,
 'AP000462.1': False,
 'SNCG': False,
 'PLPP4': False,
 'VWF': False,
 'CCDC65': False,
 'LINC02388': True,
 'RFX4': False,
 'PCDH9-AS2': True,
 'IFI27L2': False,
 'AC025043.1': False,
 'SNHG19': True,
 'GABARAP': False,
 'SLC47A1': False,
 'AC005726.5': False,
 'CRLF3': False,
 'KRT17': False,
 'GREB1L': False,
 'LAMP5': False,
 'SNAP25-AS1': True,
 'ESF1': False,
 'ROMO1': False,
 'AL109930.1': False,
 'CIRBP': False,
 'UQCR11': False,
 'PET100': False,
 'CRLF1': False,
 'AC011468.3': False,
 'NDUFA3': False,
 'TIMP3': False,
 'LGALS1': False,
 'BAIAP2L2': False,
 'ERG': False,
 'KAZN': False,
 'DAB1': False,
 'PATJ': False,
 'SLC44A5': False,
 'ST6GALNAC3': False,
 'LINC01725': True,
 'MIR181A1HG': True,
 'SLC35F3': False,
 'CNTNAP5': False,
 'COBLL1': False,
 'SCHLAP1': True,
 'VWC2L': False,
 'CNTN4': False,
 'AC092422.1': False,
 'RARB': False,
 'AC092691.1': False,
 'CLSTN2': False,
 'PEX5L': False,
 'KCTD8': False,
 'UNC5C': False,
 'INPP4B': False,
 'FSTL5': False,
 'MARCH1': False,
 'CDH18': False,
 'CDH12': False,
 'SPOCK1': False,
 'GRM4': False,
 'AL445250.1': False,
 'RIMS1': False,
 'GRIK2': False,
 'SLC35F1': False,
 'PDE7B': False,
 'POU6F2': False,
 'GRM3': False,
 'FOXP2': False,
 'KCND2': False,
 'GRM8': False,
 'PCDH11X': False,
 'IL1RAPL2': False,
 'AL078639.1': False,
 'UNC5D': False,
 'SNTG1': False,
 'TOX': False,
 'AC022639.1': False,
 'AC090568.2': False,
 'SLC22A10': False,
 'CNTN5': False,
 'PLXDC2': False,
 'SOX5': False,
 'PDZRN4': False,
 'FAM19A2': False,
 'GRIP1': False,
 'RORA': False,
 'HS3ST4': False,
 'CNTNAP4': False,
 'WWOX': False,
 'ASIC2': False,
 'DCC': False,
 'PTPRT': False,
 'TSHZ2': False,
 'SYN3': False,
 'FP671120.1': False,
 'FP236383.1': False,
 'PADI2': False,
 'NFIA': False,
 'AC244021.1': False,
 'KCNJ10': False,
 'SOX13': False,
 'CYP1B1-AS1': True,
 'ZFP36L2': False,
 'FSHR': False,
 'RTKN': False,
 'AC105402.3': False,
 'KCNH7': False,
 'LRP2': False,
 'ZNF804A': False,
 'RFTN2': False,
 'KCNH8': False,
 'LRRC3B': False,
 'SEMA3B': False,
 'ROBO2': False,
 'MTRNR2L12': False,
 'PLCH1': False,
 'FGFR3': False,
 'AC016687.2': False,
 'SPP1': False,
 'GRID2': False,
 'ETNPPL': False,
 'UGT8': False,
 'LINC01378': True,
 'AC079380.1': False,
 'TLL1': False,
 'SPOCK3': False,
 'FBXL7': False,
 'SLC1A3': False,
 'GDNF-AS1': True,
 'VCAN': False,
 'SLC27A6': False,
 'AC109466.1': False,
 'AC008415.1': False,
 'MOG': False,
 'DAAM2': False,
 'QKI': False,
 'EGFR': False,
 'HIP1': False,
 'PON2': False,
 'DLX6-AS1': True,
 'PTPRZ1': False,
 'GPR37': False,
 'CHRM2': False,
 'PLP1': False,
 'COL4A5': False,
 'DOCK5': False,
 'ST18': False,
 'CHD7': False,
 'PREX2': False,
 'LINC01608': True,
 'ENPP2': False,
 'NFIB': False,
 'TRPM3': False,
 'CDKN1C': False,
 'FOLH1': False,
 'MYRF': False,
 'HEPACAM': False,
 'ADARB2': False,
 'ITIH5': False,
 'ZCCHC24': False,
 'FGFR2': False,
 'C10orf90': False,
 'NKX6-2': False,
 'SLCO1A2': False,
 'CUX2': False,
 'RGCC': False,
 'DACH1': False,
 'HSPA2': False,
 'CLMN': False,
 'BCL11B': False,
 'AC110023.1': False,
 'FA2H': False,
 'ASPA': False,
 'TBC1D3D': False,
 'CA10': False,
 'ABCA8': False,
 'TTYH2': False,
 'TMC6': False,
 'CDH20': False,
 'CBLN2': False,
 'CNDP1': False,
 'ADAM33': False,
 'KIAA1755': False,
 'PLPP2': False,
 'MAG': False,
 'CD22': False,
 'NCAM2': False,
 'OLIG1': False,
 'RCAN3': False,
 'HDAC1': False,
 'COL9A2': False,
 'AL358075.2': False,
 'ROR1': False,
 'DIRAS3': False,
 'TXNIP': False,
 'S100A1': False,
 'PAQR6': False,
 'GLUL': False,
 'GPR37L1': False,
 'TMEM63A': False,
 'AC012593.1': False,
 'EFEMP1': False,
 'VRK2': False,
 'MEIS1': False,
 'MAL': False,
 'C1QL2': False,
 'AC096558.2': False,
 'ERMN': False,
 'TANC1': False,
 'WIPF1': False,
 'COL5A2': False,
 'INO80D': False,
 'SP100': False,
 'EFHD1': False,
 'DGKD': False,
 'LINC01811': True,
 'PLXNB1': False,
 'ADAMTS9': False,
 'ADAMTS9-AS2': True,
 'EPHA6': False,
 'ITGB5': False,
 'ALDH1L1': False,
 'KLF15': False,
 'SLC9A9': False,
 'PLSCR4': False,
 'ZIC1': False,
 'AC092958.1': False,
 'SOX2': False,
 'DGKG': False,
 'RGS12': False,
 'AC098829.1': False,
 'NPFFR2': False,
 'ARHGAP24': False,
 'PDLIM5': False,
 'DDX60L': False,
 'TENM3': False,
 'PDLIM3': False,
 'LINC02196': True,
 'SEMA5A': False,
 'CDH6': False,
 'SELENOP': False,
 'ITGA2': False,
 'SV2C': False,
 'IQGAP2': False,
 'DHFR': False,
 'RASGRF2': False,
 'SLC25A48': False,
 'SPARC': False,
 'RASGEF1C': False,
 'DDR1': False,
 'COL9A1': False,
 'GJA1': False,
 'CTGF': False,
 'AL133346.1': False,
 'SAMD5': False,
 'EZR': False,
 'SDK1': False,
 'AC004852.2': False,
 'AC004949.1': False,
 'AQP1': False,
 'ANLN': False,
 'HGF': False,
 'PDK4': False,
 'PTN': False,
 'DENND2A': False,
 'PRKX': False,
 'XIST': True,
 'AFF2': False,
 'SGCZ': False,
 'SLC7A2': False,
 'AC027117.2': False,
 'ADRA1A': False,
 'RGS20': False,
 'BHLHE22': False,
 'ZFHX4': False,
 'PMP2': False,
 'CA2': False,
 'AC037486.1': False,
 'NDRG1': False,
 'LINC02055': True,
 'ABCA1': False,
 'LINC01505': True,
 'SVEP1': False,
 'LPAR1': False,
 'COL27A1': False,
 'AL359091.1': False,
 'AIF1L': False,
 'MRPL41': False,
 'MTRNR2L8': False,
 'LUZP2': False,
 'PRR5L': False,
 'MTA2': False,
 'EML3': False,
 'NEAT1': True,
 'CARNS1': False,
 'CCND1': False,
 'GPR83': False,
 'MAML2': False,
 'TMEM123': False,
 'TAGLN': False,
 'VIM': False,
 'ALOX5': False,
 'AC074327.1': False,
 'LINC00844': True,
 'TSPAN15': False,
 'CHST3': False,
 'OPALIN': False,
 'EMX2OS': True,
 'HTRA1': False,
 'A2ML1-AS1': True,
 'PDE3A': False,
 'TMTC1': False,
 'RAPGEF3': False,
 'WIF1': False,
 'BEST3': False,
 'LGR5': False,
 'AC090502.1': False,
 'TMCC3': False,
 'MYBPC1': False,
 'BTBD11': False,
 'LINC00507': True,
 'TMEM132C': False,
 'POSTN': False,
 'FOXO1': False,
 'CLDN10': False,
 'ZIC2': False,
 'PABPN1': False,
 'LINC00639': True,
 'PLEKHG3': False,
 'ZFP36L1': False,
 'SMOC1': False,
 'STON2': False,
 'PRIMA1': False,
 'GREM1': False,
 'MEIS2': False,
 'CPLX3': False,
 'MFGE8': False,
 'EMP2': False,
 'GPRC5B': False,
 'NUPR1': False,
 'MYLPF': False,
 'NKD1': False,
 'TOX3': False,
 'MT1M': False,
 'MT1G': False,
 'CPNE2': False,
 'MAF': False,
 'AC009063.2': False,
 'AC134312.4': False,
 'PIEZO1': False,
 'CDH15': False,
 'AC055811.2': False,
 'TMEM98': False,
 'LHX1-DT': True,
 'LHX1': False,
 'GFAP': False,
 'SOX9': False,
 'SLC9A3R1': False,
 'GRIN2C': False,
 'TMEM235': False,
 'LGALS3BP': False,
 'APCDD1': False,
 'RIT2': False,
 'SLC14A1': False,
 'AC114689.3': False,
 'RIN2': False,
 'ACSS1': False,
 'SDC4': False,
 'COL20A1': False,
 'IZUMO4': False,
 'ANGPTL4': False,
 'ISYNA1': False,
 'PPP1R14A': False,
 'APOE': False,
 'HIF3A': False,
 'PCDH11Y': False,
 'USP9Y': False,
 'NLGN4Y': False,
 'TTTY14': True,
 'SOX10': False,
 'MLC1': False,
 'CHODL': False,
 'OLIG2': False,
 'RUNX1': False,
 'ITGB2': False,
 'PCBP3': False,
 'S100B': False,
 'NES': False,
 'RGS5': False,
 'PRELP': False,
 'CDK18': False,
 'PROX1': False,
 'EPHX1': False,
 'LINC01828': True,
 'MTHFD2': False,
 'RPRM': False,
 'NR4A2': False,
 'ACVR1C': False,
 'AC010127.1': False,
 'CLK1': False,
 'NEU4': False,
 'RTP5': False,
 'ZNF385D-AS2': True,
 'PTH1R': False,
 'SYNPR': False,
 'MITF': False,
 'BCL6': False,
 'LGI2': False,
 'PARM1': False,
 'RAB3C': False,
 'PDE8B': False,
 'SERPINB9': False,
 'HIST1H2AC': False,
 'VIP': False,
 'OPRM1': False,
 'VSTM2A': False,
 'SEMA3E': False,
 'SEMA3A': False,
 'TSC22D4': False,
 'ZC3HAV1': False,
 'MID1IP1': False,
 'NDP': False,
 'PDZD4': False,
 'MTUS1': False,
 'AC120193.1': False,
 'ZNF703': False,
 'FGFR1': False,
 'AC060765.1': False,
 'MYORG': False,
 'RORB': False,
 'TLE4': False,
 'SLC31A2': False,
 'NACC2': False,
 'ABCA2': False,
 'CDC42EP2': False,
 'BIRC3': False,
 'MCAM': False,
 'CRTAM': False,
 'DEPP1': False,
 'PKP2': False,
 'PAWR': False,
 'STXBP6': False,
 'IFI27': False,
 'INF2': False,
 'ISLR': False,
 'QPRT': False,
 'RRAD': False,
 'ACADVL': False,
 'HCRT': False,
 'AQP4': False,
 'MRO': False,
 'PLTP': False,
 'HRH3': False,
 'MIDN': False,
 'HMG20B': False,
 'KLF2': False,
 'RFXANK': False,
 'BCAM': False,
 'AC093503.2': False,
 'EMP3': False,
 'KLK7': False,
 'RASD2': False,
 'MPST': False,
 'CHADL': False,
 'TSPO': False,
 'ADAMTS1': False,
 'TIAM1': False,
 'HHAT': False,
 'SLC38A11': False,
 'CYP27A1': False,
 'RBMS3': False,
 'ALCAM': False,
 'LINC01322': True,
 'SLIT2': False,
 'CFAP299': False,
 'PTPN13': False,
 'STPG2': False,
 'PLCXD3': False,
 'EDIL3': False,
 'CCNH': False,
 'ADAMTS19': False,
 'FKBP5': False,
 'PTPRK': False,
 'DGKB': False,
 'CADPS2': False,
 'ALDH1A1': False,
 'AP003066.1': False,
 'SFMBT2': False,
 'KCNIP2': False,
 'ITPR2': False,
 'TRHDE': False,
 'GPC5': False,
 'LINC00609': True,
 'PELI2': False,
 'CCDC175': False,
 'CEMIP': False,
 'AC007614.1': False,
 'PLCB4': False,
 'SLC2A5': False,
 'TMEM51': False,
 'C1QB': False,
 'AC099792.1': False,
 'LINC01781': True,
 'CDC14A': False,
 'COL11A1': False,
 'ZBTB7B': False,
 'HSPA6': False,
 'TP53BP2': False,
 'SEPT10': False,
 'GALNT5': False,
 'ERBB4': False,
 'ASIC4': False,
 'SH3BP4': False,
 'GRIP2': False,
 'STAC': False,
 'IL17RB': False,
 'EPHA3': False,
 'ARHGAP31': False,
 'HCLS1': False,
 'HEG1': False,
 'BCHE': False,
 'GABRG1': False,
 'GPRIN3': False,
 'BMPR1B': False,
 'SLC12A7': False,
 'CDH9': False,
 'GHR': False,
 'AC008574.1': False,
 'MEGF10': False,
 'CD74': False,
 'SLIT3': False,
 'CPLX2': False,
 'RREB1': False,
 'HLA-E': False,
 'HS3ST5': False,
 'AL078590.3': False,
 'NXPH1': False,
 'AC007091.1': False,
 'INHBA': False,
 'AC005064.1': False,
 'AASS': False,
 'NRG1': False,
 'SFRP1': False,
 'ANGPT1': False,
 'CDKN2A': False,
 'PSAT1': False,
 'IFITM3': False,
 'LMO2': False,
 'CD82': False,
 'SERPINH1': False,
 'FAM181B': False,
 'ARHGAP42': False,
 'HEPN1': False,
 'ITGA8': False,
 'BAG3': False,
 'EPS8': False,
 'SLCO1C1': False,
 'TAC3': False,
 'NXPH4': False,
 'NEK3': False,
 'NDRG2': False,
 'ARHGEF40': False,
 'PYGO1': False,
 'UACA': False,
 'ACSBG1': False,
 'AC091078.1': False,
 'Z69706.1': False,
 'AC138305.1': False,
 'AC004158.1': False,
 'AC105411.1': False,
 'CAVIN1': False,
 'RHBDF2': False,
 'FAM69C': False,
 'GALR1': False,
 'PHF21B': False,
 'AJ009632.2': False,
 'FAM19A1': False,
 'ROBO1': False,
 'ZBTB20': False,
 'SLC4A4': False,
 'GALNTL6': False,
 'ZNF804B': False,
 'LRRC4C': False,
 'PRKG1': False,
 'SRGAP1': False,
 'PRKD1': False,
 'PDE4B': False,
 'KIF26B': False,
 'GALNT13': False,
 'CNTN6': False,
 'SORCS2': False,
 'LINC02232': True,
 'SHROOM3': False,
 'FRAS1': False,
 'FAM160A1': False,
 'SGCD': False,
 'COL21A1': False,
 'SGK1': False,
 'AC073332.1': False,
 'PDE1C': False,
 'CALN1': False,
 'PTCHD1-AS': True,
 'AC233296.1': False,
 'ZFPM2': False,
 'GLIS3': False,
 'PLPPR1': False,
 'GSN': False,
 'OAF': False,
 'GFRA1': False,
 'SLC6A12': False,
 'AC025159.1': False,
 'TMEM132D': False,
 'HS6ST3': False,
 'NPAS3': False,
 'LINC00923': True,
 'ADAMTS17': False,
 'PCSK6': False,
 'AC008105.3': False,
 'PITPNC1': False,
 'MIR646HG': True,
 'PDE1A': False,
 'CTDSP1': False,
 'CTNNB1': False,
 'CAMK2N2': False,
 'CCNG2': False,
 'CAMK2D': False,
 'NREP': False,
 'HLA-DPB1': False,
 'PRDM1': False,
 'ATP11C': False,
 'AL807761.4': False,
 'MAMDC4': False,
 'DDIT4': False,
 'METTL7A': False,
 'AC051619.4': True,
 'GATM': False,
 'CALB2': False,
 'ATP1B2': False,
 'NXPH3': False,
 'CDC42EP4': False,
 'MYL12A': False,
 'EPB41': False,
 'OLFM3': False,
 'CRB1': False,
 'ESRRG': False,
 'CCDC85A': False,
 'NXPH2': False,
 'AC073050.1': False,
 'TMEFF2': False,
 'PLCL1': False,
 'IQCA1': False,
 'FAM19A4': False,
 'CRYBG3': False,
 'PCDH7': False,
 'NWD2': False,
 'AC124854.1': False,
 'HTR4': False,
 'COL19A1': False,
 'KCNQ5': False,
 'COL12A1': False,
 'ARHGAP18': False,
 'POT1-AS1': True,
 'AC010099.4': False,
 'ANKRD18A': False,
 'AP000943.3': False,
 'PDGFD': False,
 'GRIA4': False,
 'KIAA1217': False,
 'TIMM23B': False,
 'MYO16': False,
 'AC245060.5': False,
 'SEZ6L': False,
 'AP001347.1': False,
 'PDE9A': False,
 'NKAIN1': False,
 'MFSD2A': False,
 'LRRC53': False,
 'GNG5': False,
 'TDO2': False,
 'PCSK1': False,
 'CXCL14': False,
 'EBF1': False,
 'ATP10B': False,
 'NRN1': False,
 'IER3': False,
 'CD24': False,
 'MAN1A1': False,
 'NPY': False,
 'SERPINE1': False,
 'MET': False,
 'TIMP1': False,
 'ITM2A': False,
 'LZTS1': False,
 'PNOC': False,
 'AC068205.1': False,
 'BICC1': False,
 'DUSP5': False,
 'C1R': False,
 'ITGBL1': False,
 'SHC4': False,
 'NR2F2': False,
 'SALL1': False,
 'TMEM88': False,
 'SEZ6': False,
 'ABCC3': False,
 'AC090125.1': False,
 'CBLN4': False,
 'GADD45B': False,
 'RASIP1': False,
 'LINC00320': True,
 'AURKAIP1': False,
 'NBL1': False,
 'STMN1': False,
 'ZNF593': False,
 'IFI6': False,
 'ATP5IF1': False,
 'MARCKSL1': False,
 'NDUFS5': False,
 'PRDX1': False,
 'C1orf56': False,
 'S100A6': False,
 'PFDN2': False,
 'ANGPTL1': False,
 'IER5': False,
 'AL136454.1': False,
 'G0S2': False,
 'MRPL55': False,
 'ID2': False,
 'OST4': False,
 'LINC02576': True,
 'PCBP1': False,
 'TMSB10': False,
 'RNF181': False,
 'COX5B': False,
 'DDX18': False,
 'MZT2B': False,
 'ATP5MC3': False,
 'NDUFB3': False,
 'TUBA4A': False,
 'SCG2': False,
 'ITM2C': False,
 'PTMA': False,
 'COPS9': False,
 'CCK': False,
 'TMA7': False,
 'ATP5ME': False,
 'CCNI': False,
 'H2AFZ': False,
 'SNHG8': True,
 'COX7C': False,
 'HINT1': False,
 'UQCRQ': False,
 'NDUFA2': False,
 'TUBB2A': False,
 'CUTA': False,
 'OOEP': False,
 'EEF1A1': False,
 'COX7A2': False,
 'ACTB': False,
 'NDUFA4': False,
 'AHR': False,
 'TOMM7': False,
 'PPIA': False,
 'LAMTOR4': False,
 'ATP6V1F': False,
 'TMSB4X': False,
 'AP1S2': False,
 'NDUFB11': False,
 'PCSK1N': False,
 'BEX5': False,
 'BEX1': False,
 'BEX3': False,
 'PGRMC1': False,
 'RNF113A': False,
 'NDUFA1': False,
 'SSR4': False,
 'AC244090.1': False,
 'LAGE3': False,
 'STMN4': False,
 'CLU': False,
 'UQCRB': False,
 'COX6C': False,
 'MAMDC2': False,
 'C9orf16': False,
 'OLFM1': False,
 'PHPT1': False,
 'EDF1': False,
 'TUBB4B': False,
 'POLR2L': False,
 'PLEKHA7': False,
 'PSMC3': False,
 'FTH1': False,
 'GNG3': False,
 'FKBP2': False,
 'TRMT112': False,
 'PRDX5': False,
 'FAU': False,
 'CFL1': False,
 'CCDC85B': False,
 'GSTP1': False,
 'HSPA8': False,
 'MRPL51': False,
 'GAPDH': False,
 'TPI1': False,
 'C12orf57': False,
 'TUBA1B': False,
 'TUBA1A': False,
 'PFDN5': False,
 'CD63': False,
 'NACA': False,
 'TXNRD1': False,
 ...}

In [ ]:
category = "is_lncRNA"

all_genes = set(updated_df["gene_og"].dropna().unique())

gene_status = (
    updated_df[["gene_og", category]]
    .drop_duplicates("gene_og")
    .set_index("gene_og")[category]
    .to_dict()
)

results = []

for agm_id in updated_df["AGM_ID"].dropna().unique():

    agm_genes = set(
        updated_df.loc[updated_df["AGM_ID"] == agm_id, "gene_og"]
        .dropna()
        .unique()
    )

    other_genes = all_genes - agm_genes

    category_in_agm = sum(gene_status[g] for g in agm_genes)
    not_category_in_agm = len(agm_genes) - category_in_agm

    category_outside = sum(gene_status[g] for g in other_genes)
    not_category_outside = len(other_genes) - category_outside

    table = [
        [category_in_agm, not_category_in_agm],
        [category_outside, not_category_outside]
    ]

    odds_ratio, pval = fisher_exact(table, alternative="greater")

    results.append({
        "AGM_ID": agm_id,
        "category": category,
        "n_genes": len(agm_genes),
        "n_category": category_in_agm,
        "prop_category": category_in_agm / len(agm_genes),
        "background_prop_category": category_outside / len(other_genes),
        "odds_ratio": odds_ratio,
        "pval": pval
    })

res_df = pd.DataFrame(results)
res_df["FDR"] = multipletests(res_df["pval"], method="fdr_bh")[1]
res_df = res_df.sort_values("FDR")
res_df

,AGM_ID,category,n_genes,n_category,prop_category,background_prop_category,odds_ratio,pval,FDR
15,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_6,is_lncRNA,260,38,0.146154,0.060206,2.671900,0.000004,0.000099
16,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_7,is_lncRNA,93,14,0.150538,0.067504,2.448042,0.005052,0.060626
14,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_12,is_lncRNA,46,7,0.152174,0.069459,2.404600,0.041396,0.331170
19,Oligodendrocytes_Oli_Cluster_12,is_lncRNA,92,10,0.108696,0.069561,1.631212,0.115105,0.690632
1,Excitatory_ExcL45RORBGABRG1_Cluster_7,is_lncRNA,78,8,0.102564,0.070093,1.516190,0.188046,0.902620
0,Excitatory_ExcL45RORBGABRG1_Cluster_0,is_lncRNA,144,12,0.083333,0.070430,1.199861,0.328024,1.000000
21,Immune_Micall_Cluster_11,is_lncRNA,203,6,0.029557,0.076069,0.369928,0.997869,1.000000
20,Oligodendrocytes_Oli_Cluster_3,is_lncRNA,136,9,0.066176,0.071734,0.917029,0.647610,1.000000
18,Astrocytes_AstDPP10_Cluster_6,is_lncRNA,98,8,0.081633,0.070829,1.166091,0.399803,1.000000
17,OPCs_OPC_Cluster_16,is_lncRNA,76,3,0.039474,0.072614,0.524853,0.918816,1.000000
13,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_1,is_lncRNA,163,2,0.012270,0.076589,0.149773,0.999951,1.000000
12,Inhibitory_InhG7_Cluster_12,is_lncRNA,51,2,0.039216,0.072197,0.524533,0.890356,1.000000
11,Inhibitory_InhG7_Cluster_10,is_lncRNA,57,2,0.035088,0.072419,0.465764,0.923814,1.000000
10,Excitatory_ExcNRGN_Cluster_15,is_lncRNA,40,2,0.050000,0.071792,0.680478,0.792167,1.000000
9,Excitatory_ExcL34RORBCUX2_Cluster_6,is_lncRNA,104,8,0.076923,0.071053,1.089506,0.467470,1.000000
8,Excitatory_ExcL6CT_Cluster_14,is_lncRNA,41,0,0.000000,0.072848,0.000000,1.000000,1.000000
7,Excitatory_ExcL35RORBPLCH1_Cluster_14,is_lncRNA,221,10,0.045249,0.074593,0.587963,0.965350,1.000000
6,Excitatory_ExcL45RORBGABRG1_Cluster_17,is_lncRNA,31,2,0.064516,0.071465,0.896063,0.661432,1.000000
5,Excitatory_ExcL45RORBGABRG1_Cluster_9,is_lncRNA,80,2,0.025000,0.073285,0.324241,0.982454,1.000000
4,Excitatory_ExcL45RORBGABRG1_Cluster_5,is_lncRNA,199,14,0.070352,0.071468,0.983197,0.567725,1.000000
3,Excitatory_ExcL45RORBGABRG1_Cluster_13,is_lncRNA,92,5,0.054348,0.072176,0.738797,0.800240,1.000000
2,Excitatory_ExcL45RORBGABRG1_Cluster_8,is_lncRNA,63,3,0.047619,0.072128,0.643214,0.840561,1.000000
22,Immune_Micall_Cluster_17,is_lncRNA,85,3,0.035294,0.072955,0.464895,0.950544,1.000000
23,Immune_Micall_Cluster_0,is_lncRNA,222,12,0.054054,0.073513,0.720174,0.888301,1.000000

In [ ]:

category = "is_unannotated"

all_genes = set(updated_df["gene_og"].dropna().unique())

gene_status = (
    updated_df[["gene_og", category]]
    .drop_duplicates("gene_og")
    .set_index("gene_og")[category]
    .to_dict()
)

results = []

for agm_id in updated_df["AGM_ID"].dropna().unique():

    agm_genes = set(
        updated_df.loc[updated_df["AGM_ID"] == agm_id, "gene_og"]
        .dropna()
        .unique()
    )

    other_genes = all_genes - agm_genes

    category_in_agm = sum(gene_status[g] for g in agm_genes)
    not_category_in_agm = len(agm_genes) - category_in_agm

    category_outside = sum(gene_status[g] for g in other_genes)
    not_category_outside = len(other_genes) - category_outside

    table = [
        [category_in_agm, not_category_in_agm],
        [category_outside, not_category_outside]
    ]

    odds_ratio, pval = fisher_exact(table, alternative="greater")

    results.append({
        "AGM_ID": agm_id,
        "category": category,
        "n_genes": len(agm_genes),
        "n_category": category_in_agm,
        "prop_category": category_in_agm / len(agm_genes),
        "background_prop_category": category_outside / len(other_genes),
        "odds_ratio": odds_ratio,
        "pval": pval
    })

res_df = pd.DataFrame(results)
res_df["FDR"] = multipletests(res_df["pval"], method="fdr_bh")[1]
res_df = res_df.sort_values("FDR")
res_df

,AGM_ID,category,n_genes,n_category,prop_category,background_prop_category,odds_ratio,pval,FDR
1,Excitatory_ExcL45RORBGABRG1_Cluster_7,is_unannotated,78,22,0.282051,0.103323,3.409368,0.000016,0.000375
15,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_6,is_unannotated,260,48,0.184615,0.099197,2.056058,0.000085,0.001018
19,Oligodendrocytes_Oli_Cluster_12,is_unannotated,92,22,0.239130,0.104079,2.705384,0.000244,0.001727
16,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_7,is_unannotated,93,22,0.236559,0.104134,2.665723,0.000288,0.001727
11,Inhibitory_InhG7_Cluster_10,is_unannotated,57,12,0.210526,0.107345,2.217544,0.018493,0.088765
14,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_12,is_unannotated,46,9,0.195652,0.108274,2.003315,0.059183,0.236732
7,Excitatory_ExcL35RORBPLCH1_Cluster_14,is_unannotated,221,30,0.135747,0.107123,1.309175,0.122864,0.421248
17,OPCs_OPC_Cluster_16,is_unannotated,76,11,0.144737,0.108921,1.384469,0.209342,0.628027
22,Immune_Micall_Cluster_17,is_unannotated,85,11,0.129412,0.109432,1.209717,0.332273,0.776072
0,Excitatory_ExcL45RORBGABRG1_Cluster_0,is_unannotated,144,17,0.118056,0.109677,1.086614,0.420372,0.776072
8,Excitatory_ExcL6CT_Cluster_14,is_unannotated,41,6,0.146341,0.109526,1.393754,0.294491,0.776072
2,Excitatory_ExcL45RORBGABRG1_Cluster_8,is_unannotated,63,8,0.126984,0.109737,1.180026,0.392415,0.776072
9,Excitatory_ExcL34RORBCUX2_Cluster_6,is_unannotated,104,13,0.125000,0.109474,1.162088,0.357725,0.776072
18,Astrocytes_AstDPP10_Cluster_6,is_unannotated,98,11,0.112245,0.110178,1.021128,0.524932,0.899884
10,Excitatory_ExcNRGN_Cluster_15,is_unannotated,40,3,0.075000,0.110998,0.649393,0.835268,1.000000
12,Inhibitory_InhG7_Cluster_12,is_unannotated,51,3,0.058824,0.111623,0.497420,0.932969,1.000000
13,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_1,is_unannotated,163,5,0.030675,0.117328,0.238074,0.999974,1.000000
6,Excitatory_ExcL45RORBGABRG1_Cluster_17,is_unannotated,31,2,0.064516,0.110998,0.552354,0.872604,1.000000
5,Excitatory_ExcL45RORBGABRG1_Cluster_9,is_unannotated,80,4,0.050000,0.112786,0.414019,0.982840,1.000000
4,Excitatory_ExcL45RORBGABRG1_Cluster_5,is_unannotated,199,18,0.090452,0.112465,0.784803,0.856428,1.000000
3,Excitatory_ExcL45RORBGABRG1_Cluster_13,is_unannotated,92,8,0.086957,0.111402,0.759669,0.814574,1.000000
20,Oligodendrocytes_Oli_Cluster_3,is_unannotated,136,9,0.066176,0.113490,0.553558,0.973915,1.000000
21,Immune_Micall_Cluster_11,is_unannotated,203,5,0.024631,0.119933,0.185302,1.000000,1.000000
23,Immune_Micall_Cluster_0,is_unannotated,222,13,0.058559,0.116723,0.470694,0.998243,1.000000

In [22]:
category = "gene_name_changed_by_hgnc"

all_genes = set(updated_df["gene_og"].dropna().unique())

gene_status = (
    updated_df[["gene_og", category]]
    .drop_duplicates("gene_og")
    .set_index("gene_og")[category]
    .to_dict()
)

results = []

for agm_id in updated_df["AGM_ID"].dropna().unique():

    agm_genes = set(
        updated_df.loc[updated_df["AGM_ID"] == agm_id, "gene_og"]
        .dropna()
        .unique()
    )

    other_genes = all_genes - agm_genes

    category_in_agm = sum(gene_status[g] for g in agm_genes)
    not_category_in_agm = len(agm_genes) - category_in_agm

    category_outside = sum(gene_status[g] for g in other_genes)
    not_category_outside = len(other_genes) - category_outside

    table = [
        [category_in_agm, not_category_in_agm],
        [category_outside, not_category_outside]
    ]

    odds_ratio, pval = fisher_exact(table, alternative="greater")

    results.append({
        "AGM_ID": agm_id,
        "category": category,
        "n_genes": len(agm_genes),
        "n_category": category_in_agm,
        "prop_category": category_in_agm / len(agm_genes),
        "background_prop_category": category_outside / len(other_genes),
        "odds_ratio": odds_ratio,
        "pval": pval
    })

res_df = pd.DataFrame(results)
res_df["FDR"] = multipletests(res_df["pval"], method="fdr_bh")[1]
res_df = res_df.sort_values("FDR")
res_df

,AGM_ID,category,n_genes,n_category,prop_category,background_prop_category,odds_ratio,pval,FDR
19,Oligodendrocytes_Oli_Cluster_12,gene_name_changed_by_hgnc,92,5,0.054348,0.019351,2.912395,0.040570,0.973686
20,Oligodendrocytes_Oli_Cluster_3,gene_name_changed_by_hgnc,136,4,0.029412,0.020343,1.459330,0.317438,0.974946
2,Excitatory_ExcL45RORBGABRG1_Cluster_8,gene_name_changed_by_hgnc,63,2,0.031746,0.020608,1.558197,0.383261,0.974946
4,Excitatory_ExcL45RORBGABRG1_Cluster_5,gene_name_changed_by_hgnc,199,5,0.025126,0.020499,1.231541,0.406227,0.974946
18,Astrocytes_AstDPP10_Cluster_6,gene_name_changed_by_hgnc,98,3,0.030612,0.020462,1.511741,0.338228,0.974946
15,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_6,gene_name_changed_by_hgnc,260,8,0.030769,0.019495,1.596639,0.168409,0.974946
8,Excitatory_ExcL6CT_Cluster_14,gene_name_changed_by_hgnc,41,2,0.048780,0.020377,2.465385,0.211465,0.974946
9,Excitatory_ExcL34RORBCUX2_Cluster_6,gene_name_changed_by_hgnc,104,4,0.038462,0.020000,1.960000,0.170450,0.974946
10,Excitatory_ExcNRGN_Cluster_15,gene_name_changed_by_hgnc,40,2,0.050000,0.020367,2.531579,0.203714,0.974946
14,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_12,gene_name_changed_by_hgnc,46,2,0.043478,0.020429,2.179545,0.250609,0.974946
13,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_1,gene_name_changed_by_hgnc,163,4,0.024540,0.020641,1.193644,0.449794,0.981369
11,Inhibitory_InhG7_Cluster_10,gene_name_changed_by_hgnc,57,1,0.017544,0.021058,0.830139,0.706150,0.996918
16,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_7,gene_name_changed_by_hgnc,93,2,0.021505,0.020931,1.028022,0.589021,0.996918
23,Immune_Micall_Cluster_0,gene_name_changed_by_hgnc,222,4,0.018018,0.021324,0.842105,0.701083,0.996918
22,Immune_Micall_Cluster_17,gene_name_changed_by_hgnc,85,2,0.023529,0.020844,1.131928,0.539104,0.996918
7,Excitatory_ExcL35RORBPLCH1_Cluster_14,gene_name_changed_by_hgnc,221,4,0.018100,0.021312,0.846471,0.697548,0.996918
12,Inhibitory_InhG7_Cluster_12,gene_name_changed_by_hgnc,51,1,0.019608,0.020993,0.932683,0.665152,0.996918
6,Excitatory_ExcL45RORBGABRG1_Cluster_17,gene_name_changed_by_hgnc,31,0,0.000000,0.021287,0.000000,1.000000,1.000000
17,OPCs_OPC_Cluster_16,gene_name_changed_by_hgnc,76,0,0.000000,0.021784,0.000000,1.000000,1.000000
5,Excitatory_ExcL45RORBGABRG1_Cluster_9,gene_name_changed_by_hgnc,80,1,0.012500,0.021310,0.581352,0.822565,1.000000
3,Excitatory_ExcL45RORBGABRG1_Cluster_13,gene_name_changed_by_hgnc,92,0,0.000000,0.021967,0.000000,1.000000,1.000000
1,Excitatory_ExcL45RORBGABRG1_Cluster_7,gene_name_changed_by_hgnc,78,1,0.012821,0.021288,0.597086,0.814564,1.000000
21,Immune_Micall_Cluster_11,gene_name_changed_by_hgnc,203,1,0.004926,0.022765,0.212509,0.989272,1.000000
0,Excitatory_ExcL45RORBGABRG1_Cluster_0,gene_name_changed_by_hgnc,144,1,0.006944,0.022043,0.310251,0.957813,1.000000

In [24]:
category = "gene_name_changed_by_hgnc"

results = []

for agm_id in updated_df["AGM_ID"].dropna().unique():

    agm_df = updated_df.loc[updated_df["AGM_ID"] == agm_id].copy()

    changed_to_protein_coding = agm_df.loc[
        (agm_df[category] == True) &
        (agm_df["biotype"] == "protein_coding")
    ]

    results.append({
        "AGM_ID": agm_id,
        "n_genes": agm_df["gene_og"].nunique(),
        "n_changed_to_protein_coding": changed_to_protein_coding["gene_og"].nunique(),
        "changed_to_protein_coding_genes": ", ".join(
            changed_to_protein_coding["gene_og"].dropna().unique()
        )
    })

res_df = pd.DataFrame(results)

res_df["prop_changed_to_protein_coding"] = (
    res_df["n_changed_to_protein_coding"] / res_df["n_genes"]
)

res_df = res_df.sort_values("n_changed_to_protein_coding", ascending=False)

res_df

,AGM_ID,n_genes,n_changed_to_protein_coding,changed_to_protein_coding_genes,prop_changed_to_protein_coding
4,Excitatory_ExcL45RORBGABRG1_Cluster_5,199,4,"CTGF, BTBD11, MYLPF, SLC9A3R1",0.020101
7,Excitatory_ExcL35RORBPLCH1_Cluster_14,221,4,"SEPT10, HIST1H2AC, SLC9A3R1, FAM69C",0.018100
9,Excitatory_ExcL34RORBCUX2_Cluster_6,104,4,"FAM19A1, FAM160A1, MARCH1, FAM19A2",0.038462
13,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_1,163,4,"H2AFZ, C9orf16, ATP5MPL, H3F3B",0.024540
23,Immune_Micall_Cluster_0,222,3,"MPP6, FAM19A2, FAM19A5",0.013514
20,Oligodendrocytes_Oli_Cluster_3,136,3,"FAM19A4, SPATA5, C11orf49",0.022059
15,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_6,260,2,"CCDC173, FAM19A4",0.007692
2,Excitatory_ExcL45RORBGABRG1_Cluster_8,63,2,"MARCH1, FAM19A2",0.031746
8,Excitatory_ExcL6CT_Cluster_14,41,2,"FAM19A1, FAM19A2",0.048780
22,Immune_Micall_Cluster_17,85,1,BTBD11,0.011765
21,Immune_Micall_Cluster_11,203,1,FAM19A1,0.004926
19,Oligodendrocytes_Oli_Cluster_12,92,1,LINC00854,0.010870
18,Astrocytes_AstDPP10_Cluster_6,98,1,MARCH2,0.010204
16,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_7,93,1,FAM196B,0.010753
12,Inhibitory_InhG7_Cluster_12,51,1,CTGF,0.019608
14,Inhibitory_InhLAMP5NRG1Rosehip_Cluster_12,46,1,C4orf48,0.021739
1,Excitatory_ExcL45RORBGABRG1_Cluster_7,78,1,C4orf48,0.012821
11,Inhibitory_InhG7_Cluster_10,57,1,FAM19A4,0.017544
10,Excitatory_ExcNRGN_Cluster_15,40,1,METTL7A,0.025000
5,Excitatory_ExcL45RORBGABRG1_Cluster_9,80,1,HIST1H2AC,0.012500
17,OPCs_OPC_Cluster_16,76,0,,0.000000
6,Excitatory_ExcL45RORBGABRG1_Cluster_17,31,0,,0.000000
3,Excitatory_ExcL45RORBGABRG1_Cluster_13,92,0,,0.000000
0,Excitatory_ExcL45RORBGABRG1_Cluster_0,144,0,,0.000000